### ISSUE TITLE
Missing jquery dependency

### ISSUE THREAD

**Issue by glasser** [Respondly/meteor-util#4]
There are lots of references to `$` in this package, but no dependency on the `jquery` package.

I discovered this while trying to run the reproduction for https://github.com/meteor/meteor/issues/4839 which used `respondly:test-reporter`.  On devel, `meteor-platform` is no longer added to all test-packages  runs by default (https://github.com/meteor/meteor/commit/9406bef6).  So that reveals the bug in this package.

**Comment by Sanjo** [comment]
:+1:

**Comment by rissem** [comment]
Fixed with https://github.com/Respondly/meteor-util/pull/5
